name: Update Database

on:
  workflow_dispatch:
  push:
    branches: 
      - main
    paths:
      - "mods.json"

permissions:
  contents: write

jobs:
  update-database:
    name: Update Database
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build
        run: |
          cd scripts
          npm install
          npm run build
      - name: Sanity check
        run: |
          cd scripts
          cd build
          pwd
          ls
      - name: Run local action
        uses: ./actions/update-database
      - name: Checkout database repo
        uses: actions/checkout@v3
        with:
          ref: database
          path: database
      - name: Copy database
        run: cp database.json database/database.json
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: database
          repository: database
          commit_message: Update mod database
          commit_user_name: Dredge Mod Database
