name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build
        run: |
          cd scripts
          npm install
          npm run build
          ls
          cd scripts
          ls 
          cd actions
          ls
      - name: Help
        run: |
          ls
          pwd
      - name: Run script
        uses: ./scripts/actions/action
        
